# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

overlapper <- function(seq1_set, seq2_set) {
    .Call(`_TranSpotteR_overlapper`, seq1_set, seq2_set)
}

replcae_space <- function(x) {
    .Call(`_TranSpotteR_replcae_space`, x)
}

t_coffee <- function(strings) {
    .Call(`_TranSpotteR_t_coffee`, strings)
}

