# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cxx_query_to_reference_position <- function(raln, qaln) {
    .Call(`_TranSpotteR_cxx_query_to_reference_position`, raln, qaln)
}

#' @export
cxx_ref_extension <- function(vecs) {
    .Call(`_TranSpotteR_cxx_ref_extension`, vecs)
}

msa_view <- function(raln, qaln) {
    .Call(`_TranSpotteR_msa_view`, raln, qaln)
}

overlapper <- function(seq1_set, seq2_set) {
    .Call(`_TranSpotteR_overlapper`, seq1_set, seq2_set)
}

replcae_space <- function(x) {
    .Call(`_TranSpotteR_replcae_space`, x)
}

t_coffee <- function(strings, match_score = 1L, mismatch_score = -1L, gap_ext_score = 0L, gap_open_score = -10L) {
    .Call(`_TranSpotteR_t_coffee`, strings, match_score, mismatch_score, gap_ext_score, gap_open_score)
}

